version: "2"
formatters:
  enable:
    - golines
    - gofumpt
  settings:
    gofumpt:
      module-path: github.com/lucidfrontier45/i
      extra-rules: true
linters:
  default: standard
  enable:
    - revive
    - copyloopvar
    - unconvert
    - nilnesserr
    - intrange
  settings:
    revive:
      severity: warning
run:
  timeout: 5m
